### PR TITLE
add buildtest project for good first issues

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
i am the lead developer of buildtest so i wanted to add this so it shows up in the first issues. I came across the hpc.social talk at EUM. Great talk btw @vsoch. 

Please let me know if i did correctly.

### CODE REVIEW

**Comment by vsoch** [comment]
Yes, perfecto! Thank you @shahzebsiddiqui !

**Comment by shahzebsiddiqui** [comment]
question for you @vsoch i take it the repo needs to have a `good first issue` looking at this code https://github.com/hpc-social/good-first-issues/blob/6b236c2f36f6ec3c337f794b2607bc5f42f1670d/.github/scripts/add-repos.py#L15.

I just created this label [good first issue](https://github.com/buildtesters/buildtest/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) in the project.

I take it this should work in the next CI build and i should be able to see it under https://hpc.social/good-first-issues/ under the `repository` dropdown 

Screen Shot 2023-04-26 at 4 24 28 PM

**Comment by vsoch** [comment]
yes it will run nightly, so should be able to find issues that were added the previous day with this label.

**Comment by shahzebsiddiqui** [comment]
i will check back in a day and hopefully it shows up in the dropdown.

**Pull request merged**
